Skip security groups w/ no protocol.
When using Nova w/ the new Quantum security groups driver security
groups can exist which have no protocol. Theses entries
cause ERROR: 'NoneType' object has no attribute 'upper'
when you try to delete other (editable) security groups.

This patch updates novaclient so that it skips over entries with
no protocol when determining which security group to delete.
This fixes novaclient so that deleting *any* security group works
when the new quantum security group driver is enabled.

Fixes LP Bug #1162622.

Change-Id: Ida07b6429eae988a9a64535381082a500f31a521