python3: Fix traceback while running unit tests
While running unit tests with python3, we get the following traceback:

TypeError: 'map' object is not subscriptable

In python3, a map returns an iterable object of type map,
and is not subscriptable.

Refactor to not use indicies so that it is python2 and python3
compat.

blueprint python3-novaclient

Change-Id: Iaf0de19f08fa3e91ee79c174ccc86a8bbe4acdc8
Signed-off-by: Chuck Short <chuck.short@canonical.com>